language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: "2.7"
    - python: "3.6"

install:
 - pip install -U pip
 - pip install -U flake8
 - pip install -U -r requirements.txt

script:
 # Static analysis
 - flake8 --statistics --count

 # Dry run
 - python whyaretheflagsup.py --test -y whyaretheflagsup_example.yaml -i flag.jpg
